✨ Feat: add ability to use example files
TanklesXL/gladvent pull request #12
Opened 2024-07-09 16:09 UTC by bucsi

My puzzle workflow is usually the following:

1. understand the task
2. write a solution
3. run the solution with the example input in the task
4. debug the solution
5. run the solution for my puzzle input
6. write solution for the 2nd part
7. repeat 3-5.

With `gladvent`, steps 5 and 7 always involve deleting my puzzle input from the input file, then copying it back.

With this PR:
- the `new` command creates a `{day}.example.txt` file as well
- I introduced a new bool flag for the `run` command, `--use-example`. If it is present, the runner will pass the example txt as input

If I missed anything, please reach out and I'll gladly update my PR.

2024-07-10 19:07 UTC, TanklesXL commented
Thanks for the contribution! I haven't looked at the code yet but upon reading the description I wonder if it's worth putting the example generation behind a flag. 

I would probably replace the `--use-example` group flag from the `run` group with a group flag of `--example` at the root so it can be used for both generation via `new` and running via `run` and `run all`.

2024-07-13 01:43 UTC, TanklesXL requested changes
Hey there! I finally got a chance to dig into these changes and'm liking where things are headed. I left a few comments, the emojis I use are explained in [this guide](https://github.com/erikthedeveloper/code-review-emoji-guide) but aren't strictly necessary for understanding the comments.

2024-07-13 01:43 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +    create_input_example_file,
💭  maybe we should make adding the example conditional on a the state of the `example` flag? That would require adding it to the `new` command as well. (the existing one could be moved to the root or the `new` command could be given it's own `example` flag so that the description is more relevant

📝 A user will always want to create to create a normal input file but not everyone will want to create example inputs, and if it's forgotten they can always rerun with `--example` to create it. This pattern is ok since rerunning the `new` command does not overwrite existing files.

2024-07-13 01:43 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +  glint.bool_flag("use-example")
🔧 since glint does not yet support short flag names let's keep flag names as short as we can while still having them make sense
```suggestion
pub fn example_flag() {
  glint.bool_flag("example")
```

2024-07-13 01:43 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +  }
⛏️ this is fine as-is, but we can use `result.map` here to avoid having to duplicate states and worry about the error case at all

2024-07-13 01:43 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
>  pub fn run_all_command() -> glint.Command(Result(List(String))) {
💭  it looks like you forgot to add example support to the `run all` command, was this intentional? If so, how come the flag was added at the group level rather than directly in the `run` command?

🔧 If leaving out the example support from the `run all` command was a mistake, please add.

2024-07-13 01:43 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +    do(year, _, package, allow_crash, input.Puzzle),
🔧 see the above comment on not having example support for the `run all` command.

2024-07-13 01:43 UTC, TanklesXL commented on src/gladvent/internal/input.gleam
> +pub type Kind {
👍 nice, i like that youve made a separate module for this

♻️  i wonder if it is worth moving other input-related things to this module like the `cmd.input_dir`

2024-07-16 17:03 UTC, bucsi commented on src/gladvent/internal/cmd/new.gleam
> +    create_input_example_file,
Agreed! Let's add the `example` flag to the new command as well.

2024-07-16 17:11 UTC, bucsi commented on src/gladvent/internal/cmd/run.gleam
> +  }
Even tho I forgot about `result.map`, seeing the alternate makes me believe the original version is more readable: 

```gleam
let assert Ok(use_example) =
    glint.get_flag(flags, example_flag())
    |> result.map(fn(flag) {
      case flag {
        True -> input.Example
        _ -> input.Puzzle
      }
    })
 ```

Even without the pipe:

```gleam
let assert Ok(use_example) =
    result.map(glint.get_flag(flags, example_flag()), fn(flag) {
      case flag {
        True -> input.Example
        _ -> input.Puzzle
      }
    })
```

2024-07-16 17:13 UTC, bucsi commented on src/gladvent/internal/cmd/run.gleam
>  pub fn run_all_command() -> glint.Command(Result(List(String))) {
My belief is that running all solutions is a feature used when all of them are done. Maybe we need user research? :smile: I'm fine with either adding it to run all, or removing it from the group level, the decision is yours :slightly_smiling_face:

2024-07-16 17:16 UTC, bucsi commented on src/gladvent/internal/input.gleam
> +pub type Kind {
:heavy_check_mark: Moving other input-related things is  a nice idea! I will work on it.

2024-07-16 17:20 UTC, bucsi commented on src/gladvent/internal/cmd/new.gleam
> +    create_input_example_file,
:thinking: How should we handle the case when a day is run with the example flag, but the example file does not exist? We might have to add a custom error message, hinting to run `new --example`.

2024-07-16 17:40 UTC, bucsi commented on src/gladvent/internal/cmd/run.gleam
>  pub fn run_all_command() -> glint.Command(Result(List(String))) {
Also, I cannot figure out how to add a flag to a command without the `group_flag`.

2024-07-16 23:50 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +    create_input_example_file,
What does it do if you try it now? For normal input missing it should print an error message, examples should have the same behaviour

2024-07-16 23:51 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +  }
Agreed, fine to keep as-is

2024-07-17 00:00 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
>  pub fn run_all_command() -> glint.Command(Result(List(String))) {
hmmm for now let's take it out of the group and apply it only to `run` and `new`. 

you would do so using [glint.flag](https://hexdocs.pm/glint/glint.html#flag)

```gleam
pub fn run_command(...)->...{
...
use is_example <- glint.flag(example_flag())
...
let assert Ok(...) =   case is_example(flags) { ... }
```

2024-07-17 00:03 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +  let seq =
🔧 this list is very short, why introduce `iterator` for this?

2024-07-17 00:07 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +  let seq =
♻️ adding example input here should only involve a slight modification of the original `seq` list

```gleam
let seq = [
    create_input_root,
    create_input_dir,
    create_input_file,
    create_input_example_file,
    create_src_dir,
    create_src_file,
    .. case ctx.create_example_file {
        True -> [create_input_example_file]
        False -> []
    }
]

2024-07-17 00:09 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +  let assert Ok(create_example) = glint.get_flag(flags, example_flag())
we can add the flag locally with `glint.flag` to use the provided fetching function, see above to use the `parse` flag example

2024-07-17 00:11 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +pub fn example_flag() {
🔧 no need to export this function if it will only be used in this module

2024-07-17 00:13 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +    "Generate example input files to run your solution against the task description's input",
🔧 This sentence can be shortened and maintain the same meaning
> Generate example input files to run your solution against.

2024-07-17 10:47 UTC, bucsi commented on src/gladvent/internal/cmd/new.gleam
> +    "Generate example input files to run your solution against the task description's input",
✔️ Thanks for rephrasing it!

2024-07-17 10:58 UTC, bucsi commented on src/gladvent/internal/cmd/new.gleam
> +  let assert Ok(create_example) = glint.get_flag(flags, example_flag())
✔️ Thanks!

2024-07-17 11:01 UTC, bucsi commented on src/gladvent/internal/cmd/new.gleam
> +pub fn example_flag() {
✔️ Removed, as I used `glint.flag()`

2024-07-18 15:30 UTC, TanklesXL requested changes
coming along nicely! left some more notes

2024-07-18 15:30 UTC, TanklesXL commented on src/gladvent.gleam
> +    |> glint.group_flag(at: ["run"], of: run.example_flag())
🔧 no need for this as a group flag as we move the example flag into the `run` command itself

2024-07-18 15:30 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +pub fn example_flag() {
🔧 let's move this into the `run` command itself, so there's no need to export it

2024-07-18 15:30 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +  let assert Ok(use_example) = case glint.get_flag(flags, example_flag()) {
🔧 use `glint.flag` here

2024-07-18 16:26 UTC, bucsi commented on src/gladvent/internal/cmd/new.gleam
> +    create_input_example_file,
I think this is descriptive enough:

```
❯ gleam run -- run 7 --example
   Compiled in 0.05s
    Running gladvent.main
error: Failed to run 2024 day 7

cause:
  0: failed to read input file: ./input/2024/7.example.txt
```

2024-07-18 16:28 UTC, bucsi commented on src/gladvent.gleam
> +    |> glint.group_flag(at: ["run"], of: run.example_flag())
✔️ Completed moving the run flag from group level to command level

2024-07-18 17:33 UTC, TanklesXL commented on src/gladvent/internal/cmd/run.gleam
> +      "Generate example input files to run your solution against",
Seems you've copied the description from the `new` command, this should 
```suggestion
      "Run solutions against example inputs (found at input/<year>/<day>.example.txt)",
```

2024-07-22 08:41 UTC, bucsi commented on src/gladvent/internal/cmd/run.gleam
> +      "Generate example input files to run your solution against",
Damn, my greatest arch enemy, copy-pasting without paying attention :D

2024-07-22 18:30 UTC, TanklesXL approved these changes

2024-07-22 18:32 UTC, merged

2024-07-22 18:33 UTC, TanklesXL commented
Thanks a bunch! merged