Add the possibility to fetch the input directly from the AoC website
TanklesXL/gladvent pull request #16
Opened 2024-11-27 18:22 UTC by renaudlenne

### Some context:
I know you had a couple reason to not have implemented this, but that's a feature that I'd really use, so as I've developed something I guessed I could try to open a PR, in case you'd be interested to merge it.

Bear with me that those are the first ever lines of code I've written in Gleam, so that's probably not very idiomatic, that's one of the reason why I'm eager to get feedback (if you are interested in the feature).

### Description
The PR adds a new `--fetch` flag to the `new` command which will fetch the input directly from the AoC website (and put it at the correct place).
It just needs to have the session cookie of the user in the `AOC_COOKIE` environment variable.

2024-11-29 08:35 UTC, TanklesXL requested changes
Looking great so far! For this being your first time writing gleam i think you're doing a great job, keep at it! 

Given these changes we should also be removing the FAQ question about input fetching being missing from the README and likely add a section on fetching input with the new flag.

2024-11-29 08:35 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +    )
🔧 2 things here: 
1. let's pull this part out into it's own function
2. since `create_input_file` is already being passed the context, we can have it decide whether to fetch the input and fill the file if the input kind is `Puzzle` and `fetch_input` is `True`

2024-11-29 08:35 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +      False -> fetch_input_list
💭  if my above suggestion to add the behaviour to the `create_input_file` function pans out then we likely won't need this `do` function to change

2024-11-29 09:31 UTC, renaudlenne commented
All good remarks, thanks!
I've pushed two new commits that should address them.

2024-11-29 23:42 UTC, TanklesXL requested changes

2024-11-29 23:42 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +  let req = request.prepend_header(base_req, "Cookie", "session="<>cookie)
🔧 if we're going to mix request builder functions with `request.to` then we might as well just use only request builder functions to construct it, that way we avoid the need to assert on a result as well

2024-11-29 23:42 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +  Ok(resp.body)
🔧 It's worth noting that `httpc.HttpError` only occurs if there is a real HTTP error, it does not account for non 2XX responses
```gleam
pub type HttpError {
  InvalidUtf8Response
  FailedToConnect(ip4: ConnectError, ip6: ConnectError)
}
```

We should be checking that the response is a success and thus the body can be used, otherwise we should be returning an error

2024-12-01 09:29 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +        use content <- result.try(download_input(ctx))
💭  in order to avoid downloading input that has already been fetched, we may to to rework this function somewhat to always attempt to create the file, and only download and fill it with input if we have successfully created it or we find a way to guarantee that the file is empty (I assume simplifies has a function we can leverage for this)

2024-12-01 17:20 UTC, renaudlenne commented on src/gladvent/internal/cmd/new.gleam
> +  Ok(resp.body)
I cannot see how we could do that with `httpc`.
When sending the request, if it's deemed successful, we only retrieve a `String` containing the body.

I agree that it's not ideal. We should probably switch to a more explicit library like `gleam_hackney` which returns a `Response` on which we can test the status.

2024-12-01 18:08 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +  Ok(resp.body)
Httpc returns a gleam_http.Response which has a status we can access once the request itself succeeds. You already access the body we just need to check the status code before accessing the body 

```gleam
pub type Response(body) {
  Response(status: Int, headers: List(Header), body: body)
}
```

2024-12-04 09:02 UTC, renaudlenne commented on src/gladvent/internal/cmd/new.gleam
> +        use content <- result.try(download_input(ctx))
As the `--fetch` is a flag to new, we could probably assume that people would run `new` only once. Wouldn't it then be simpler to just assume we don't want to do anything if the file already exists, and then throw the same `FileAlreadyExists` error as when trying to create it? Checking for emptiness seems a bit excessive.

2024-12-04 09:30 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +        use content <- result.try(download_input(ctx))
Yeah that works too! in that case we create as normal and let that fail/succeed and then only write the contents if the create succeeded

2024-12-04 09:35 UTC, renaudlenne commented on src/gladvent/internal/cmd/new.gleam
> +        use content <- result.try(download_input(ctx))
I have explicitly checked for file existence to avoid having to create an empty file (see my last commit), but you'd maybe have preferred to always call the `create_file` function and then call `download_input` only if `create_file` succeeded (thus the file wasn't there before) and we fill the conditions (input kind and flag).
I can rewrite that if you think it's best and/or easier to maintain.

2024-12-05 12:47 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +          simplifile.is_directory(input_path)
🔧 we can probably replace this with a single call to [`simplifile.file_info`](https://hexdocs.pm/simplifile/simplifile.html#file_info), it should error if the file/directory doesn't exist (worth checking that it works for directories at least)

2024-12-05 12:50 UTC, TanklesXL commented on src/gladvent/internal/cmd/new.gleam
> +    FailedToWriteToFile(e) -> "failed to write to file:" <> string.inspect(e)
🔧 use [`simplifile.describe_error`](https://hexdocs.pm/simplifile/simplifile.html#describe_error) to get a human-readable error rather than inspecting the value which will result in a not-so-helpful string

2024-12-05 13:27 UTC, renaudlenne commented on src/gladvent/internal/cmd/new.gleam
> +          simplifile.is_directory(input_path)
Interesting. I took this test from the  `create_file` [source](https://github.com/bcpeinhardt/simplifile/blob/0d0f2f082a2d90806c54565dac64e1b4a659a3d0/src/simplifile.gleam#L473) but I agree that having a single call to `file_info` would probably be more efficient.

2024-12-06 15:49 UTC, TanklesXL commented
Thanks a bunch!

2024-12-06 15:50 UTC, merged