Pad filenames with zeros by default
TanklesXL/gladvent pull request #22
Opened 2024-12-05 23:24 UTC by logan-connolly

This change sets the default behavior for newly created solutions to have padding by default (#18).

```
input/2024/1.txt -> input/2024/01.txt
src/aoc_2024/day_1.gleam -> src/aoc_2024/day_01.gleam
```
To not break existing solutions, filenames without padding will be handled and processed as before.

### Sanity check that legacy filenames still work

![image](https://github.com/user-attachments/assets/1ff5a176-15e3-4144-8197-9a289a59a60f)

### Create new day solution

![image](https://github.com/user-attachments/assets/92ccfed4-c435-420e-8bd0-53e5c49c406d)

2024-12-11 17:13 UTC, TanklesXL requested changes
Looking good! Are you planning on sending the `upgrade` command in a separate PR?

2024-12-11 17:13 UTC, TanklesXL commented on src/gladvent/internal/runners.gleam
> +  let module_name = handle_module_name(year, day, module_exists)
🔧 `gleam/dict` has a `has_key` function so there's no reason to use `list.contains`

```suggestion
  let module_name = handle_module_name(year, day, dict.has_key(package.modules, _))
```

2024-12-15 12:32 UTC, logan-connolly commented on src/gladvent/internal/runners.gleam
> +  let module_name = handle_module_name(year, day, module_exists)
Good catch!

> upgrade command in a separate PR?

Yeah, exactly. Will pick that up in a follow up PR. Hopefully, I have some time over the holiday to tackle it.

2024-12-18 17:12 UTC, TanklesXL approved these changes
Looking good!

2024-12-18 17:13 UTC, merged